### ISSUE TITLE
move omero-install to ONBUILD RUN

### ISSUE THREAD

**Issue by atarkowska** [openmicroscopy/devslave-c7-docker#8]
@sbesson reported that would be nice to have vanilla devslave Dockerfile that can be adapted to various OME purposes. Removing omero-install and adding `ONBUILD RUN run.sh` https://docs.docker.com/engine/reference/builder/#/onbuild adds to the image a trigger instruction to be executed at a later time, when the image is used as the base for another build. I will refactor this and provide an example via devspace. 

I am also guessing, once that happen we should move that repo to http://github.com/ome/

**Comment by jburel** [comment]
N/A
